toolbox4minecraft/amidst

.travis.yml, README.md, docs/building-amidst-from-source-code.md, docs/getting-involved.md, docs/how-can-i-move-a-player.md, docs/releasing-amidst.md
This pull request contains fixes for the repository, so it works correctly after the move to toolbox4minecraft/amdist. It also contains changes in the documentation.
=> Adjustments after move to organization

src/devtools/java/amidst/devtools/GenerateUpdateInformationJson.java, src/main/java/amidst/AmidstMetaData.java, src/main/java/amidst/AmidstVersion.java, src/main/java/amidst/Application.java, src/main/java/amidst/gui/main/Actions.java, src/main/java/amidst/gui/main/MainWindow.java, src/main/java/amidst/gui/main/UpdateInformationJson.java, src/main/java/amidst/gui/main/UpdateInformationRetriever.java, src/main/java/amidst/gui/main/UpdatePrompt.java, src/main/resources/amidst/metadata.properties
This pull request adjusts the update mechanism:
* changed the URL of the update information document to https://toolbox4minecraft.github.io/amidst/api/update-information.json
* changed the format to json, so we can use gson to read and generate the document
* added devtool to generate the update information document
* the check for updates is now executed only once, when the application is started, and when the user asks for it
* added an optional message to the update information document
=> Adjusting update mechanism

src/main/java/amidst/gui/main/Actions.java
* updated the How can I move a player dialog to match the description in the wiki
* updated text in about window
=> updated gui texts

src/main/java/amidst/Amidst.java, src/main/java/amidst/AmidstVersion.java, src/main/java/amidst/Application.java, src/main/java/amidst/CommandLineParameters.java, src/main/java/amidst/gui/main/MainWindow.java, src/main/java/amidst/mojangapi/MojangApi.java, src/main/java/amidst/mojangapi/MojangApiBuilder.java, src/main/java/amidst/mojangapi/file/directory/DotMinecraftDirectory.java, src/main/java/amidst/mojangapi/world/SeedHistoryLogger.java, src/main/java/amidst/settings/biomecolorprofile/BiomeColorProfileDirectory.java
* added -version and -help parameters
* fixed -mcjson parameter to be only used for the first loaded version directory
* fixed -mcjar and -mcjson, so only both can be used, or none of them
* in the case of a parameter parsing exception, the usage informations are now displayed
* made the usage information more readable
* sorted the parameters for the usage printing
* added logging for the used parameters
=> enhanced cli

src/main/java/amidst/gui/main/MainWindow.java, src/main/java/amidst/mojangapi/file/directory/ProfileDirectory.java
* made the saves directory in the profile directory optional
* possible fix for issue #26
=> Bug fixing

src/main/java/amidst/Amidst.java, src/main/java/amidst/gui/crash/CrashWindow.java
* added request to create a github issue for the crash
* added url to create a github issue
* url is copyable
* removed noisy text
=> Improved usability of the crash window

src/main/java/amidst/mojangapi/file/nbt/LevelDatNbt.java, src/main/java/amidst/mojangapi/file/nbt/NBTTagKeys.java, src/main/java/amidst/mojangapi/file/nbt/NBTUtils.java, src/main/java/amidst/mojangapi/world/WorldBuilder.java, src/main/java/amidst/mojangapi/world/icon/producer/SpawnProducer.java, src/main/java/amidst/mojangapi/world/icon/type/DefaultWorldIconTypes.java, src/main/java/amidst/mojangapi/world/oracle/HeuristicWorldSpawnOracle.java, src/main/java/amidst/mojangapi/world/oracle/ImmutableWorldSpawnOracle.java, src/main/java/amidst/mojangapi/world/oracle/WorldSpawnOracle.java
=> the world spawn is now read from the level.dat file

src/main/java/amidst/mojangapi/world/icon/type/EndCityWorldIconTypeProvider.java
Fixes bug where the influence of all nearby islands wasn't taken into account.
=> Make End cities more accurate

travis-ci/wrapper-for-windows/pom.xml
=> enabled stayAlive for windows wrapper

src/main/java/amidst/mojangapi/world/versionfeatures/DefaultVersionFeatures.java
This is also the behavior of Amidst v3.7.
=> re-enabled the move and save player functionality for UNKNOWN versions

src/main/java/amidst/gui/main/Actions.java, src/main/java/amidst/gui/main/viewer/ViewerFacade.java, src/main/java/amidst/gui/main/viewer/widget/SeedWidget.java, src/main/java/amidst/gui/main/viewer/widget/SelectedIconWidget.java, src/main/java/amidst/gui/main/viewer/widget/WidgetBuilder.java, src/main/java/amidst/gui/main/viewer/widget/WorldTypeWidget.java, src/main/java/amidst/mojangapi/world/WorldType.java
=> Add world type to screen and screenshot filename

src/main/java/amidst/gui/main/Actions.java, src/main/java/amidst/gui/main/MainWindow.java, src/main/java/amidst/gui/main/menu/AmidstMenuBuilder.java, src/main/java/amidst/mojangapi/MojangApi.java, src/main/java/amidst/mojangapi/world/WorldBuilder.java, src/main/java/amidst/mojangapi/world/WorldSeed.java
This contains pretty much only rename refactorings, which should not introduce any bugs.
=> unified terminology for the term "save game"

src/main/java/amidst/gui/main/Actions.java, src/main/java/amidst/gui/main/MainWindow.java
The user now has to explicitly confirm each save game manipulation.
=> added warning about save game manipulation

src/main/java/amidst/mojangapi/world/player/WorldPlayerType.java
It did not work correctly if there where no player information at all, which is indeed pretty unlikely.
=> fixed world player type detection

src/main/java/amidst/gui/main/Actions.java, src/main/java/amidst/mojangapi/world/icon/producer/StrongholdProducer_128Algorithm.java, src/main/java/amidst/mojangapi/world/icon/producer/StrongholdProducer_Buggy128Algorithm.java, src/main/java/amidst/mojangapi/world/icon/producer/StrongholdProducer_Original.java
* tests whether target file is a directory
* tests if target file is writable
* asks if existing target file should be replaced
=> Screenshot file handling

src/main/java/amidst/Amidst.java, src/main/java/amidst/gui/main/viewer/widget/DebugWidget.java
* the recognition of windows was buggy
* the environment variables need to be set before the look and feel
This should enable the acceleration on windows.
=> fixing java2d

src/main/java/amidst/gui/main/viewer/Viewer.java
It occured when the window was dragged to another monitor.
=> fixed a NPE for multi-monitor setups

src/main/java/amidst/Amidst.java, src/main/java/amidst/AmidstSettings.java, src/main/java/amidst/gui/main/Actions.java, src/main/java/amidst/gui/main/menu/AmidstMenuBuilder.java
Fixes #43, and probably fixes #81
=> Fix 2D acceleration issues on Windows

src/test/java/amidst/devtools/DevToolRunner.java, src/test/java/amidst/devtools/GenerateBiomeColorImages.java, src/test/java/amidst/devtools/settings/DevToolSettings.java, src/test/resources/amidst/devtools/devtools.properties.template
This does not change the production code base.
=> added the devtool GenerateBiomeColorImages

src/main/java/amidst/gui/main/menu/AmidstMenuBuilder.java, src/main/java/amidst/gui/main/menu/LayersMenu.java, src/main/java/amidst/gui/main/menu/Menus.java, src/main/java/amidst/settings/Setting.java, src/main/java/amidst/threading/ThreadMaster.java
This pull request fixes the issue #98.
=> Fix menu shortcuts on OS X

src/main/java/amidst/fragment/FragmentGraph.java, src/main/java/amidst/util/Lazy.java
I introduced a new class called Lazy to prevent this from happening again.
Fixes #115
=> fixed the NPE in the fragment graph

src/main/java/amidst/gui/main/Actions.java, src/main/java/amidst/gui/main/menu/AmidstMenuBuilder.java, src/main/java/amidst/mojangapi/MojangApi.java, src/main/java/amidst/mojangapi/file/json/JsonReader.java, src/main/java/amidst/mojangapi/file/json/filter/BiomeFilterJson.java, src/main/java/amidst/mojangapi/file/json/filter/StructureFilterJson.java, src/main/java/amidst/mojangapi/file/json/filter/WorldFilterJson.java, src/main/java/amidst/mojangapi/world/filter/BaseFilter.java, src/main/java/amidst/mojangapi/world/filter/BiomeFilter.java, src/main/java/amidst/mojangapi/world/filter/StructureFilter.java, src/main/java/amidst/mojangapi/world/filter/WorldFilter.java, src/main/java/amidst/mojangapi/world/filter/WorldFinder.java, src/main/java/amidst/mojangapi/world/icon/type/DefaultWorldIconTypes.java
Addresses #120. See original PR #123 for more comments.
Working search configured by a search.json file in the home directory. Feature work:
=> Working filtered random seed demo

src/main/java/amidst/mojangapi/world/biome/Biome.java, src/main/java/amidst/mojangapi/world/biome/BiomeType.java, src/main/java/amidst/mojangapi/world/versionfeatures/DefaultVersionFeatures.java
I was browsing the source code and I saw that this class did not have clear names.
The names of the types are not taken from the game ; they are guesses based on the biomes they contain, but I think they are accurate.
=> Add better naming for BiomeType class.

src/main/java/amidst/mojangapi/file/LibraryFinder.java, src/main/java/amidst/mojangapi/file/json/version/LibraryJson.java, src/main/java/amidst/mojangapi/file/json/version/LibraryRuleJson.java, src/main/java/amidst/mojangapi/file/json/version/LibraryRuleOsJson.java, src/main/java/amidst/util/OperatingSystemDetector.java
=> added os version recognition for libraries

src/main/java/amidst/gui/main/Actions.java, src/main/java/amidst/gui/main/MainWindow.java, src/main/java/amidst/gui/main/menu/AmidstMenuBuilder.java
This replaces the old shortcuts + and - by CTRL+G and CTRL+H.
This implements #194.
=> added zoom menu entries and shortcuts

src/main/java/amidst/mojangapi/world/WorldBuilder.java, src/main/java/amidst/mojangapi/world/versionfeatures/DefaultVersionFeatures.java, src/main/java/amidst/mojangapi/world/versionfeatures/VersionFeatures.java
Nobody seems to know why it exists in the first place and to me it does not make sense.
=> removed version dependent isSaveEnabled flag

src/main/java/amidst/gui/main/PerMainWindowInjector.java, src/main/java/amidst/gui/profileselect/LocalProfileComponent.java, src/main/java/amidst/mojangapi/file/LauncherProfile.java, src/main/java/amidst/mojangapi/file/MinecraftInstallation.java, src/main/java/amidst/mojangapi/file/UnresolvedLauncherProfile.java, src/test/java/amidst/devtools/GenerateInstalledVersionsList.java
We now determine the underlying vanilla Minecraft version and use that instead. We also inform the user about this.
=> kind of added support for modded Minecraft

README.md
Fixed some small typos and grammar mistakes in the README
=> Copyediting

src/main/java/amidst/Amidst.java
=> Use screen menu bar on OSX.

src/main/java/amidst/gui/main/menu/AmidstMenuBuilder.java
I may have gotten a few ellipsis placements wrong, but I fixed most of the capitalization.
=> Fix some menu namings based off issue #650

src/main/java/amidst/mojangapi/minecraftinterface/RecognisedVersion.java, src/main/java/amidst/mojangapi/world/WorldBuilder.java, src/main/java/amidst/mojangapi/world/WorldSeed.java, src/main/java/amidst/mojangapi/world/versionfeatures/DefaultVersionFeatures.java, src/main/java/amidst/mojangapi/world/versionfeatures/VersionFeatures.java
Also fixes some seeds being impossible to generate when making a random seed
=> Add 20w06a to versions list, fix ocean features placement for 20w06a

src/main/java/amidst/gui/main/viewer/Graphics2DAccelerationCounter.java, src/main/java/amidst/gui/main/viewer/widget/BiomeWidget.java, src/main/java/amidst/mojangapi/file/service/DownloadService.java, src/main/java/amidst/mojangapi/minecraftinterface/local/DefaultClassTranslator.java, src/main/java/amidst/mojangapi/world/versionfeatures/VersionFeatures.java, src/main/java/amidst/settings/SettingBase.java, src/main/java/amidst/settings/biomeprofile/BiomeProfileDirectory.java
Decided to run spotbugs on the project. Fixed the ones that I could that showed up. Nothing really too special.
=> Fix a couple possible bugs

src/main/java/amidst/mojangapi/file/nbt/LevelDatNbt.java
=> Fix not properly detecting large biomes

src/main/java/amidst/AmidstSettings.java, src/main/java/amidst/fragment/drawer/ImageDrawer.java, src/main/java/amidst/fragment/drawer/WorldIconDrawer.java, src/main/java/amidst/fragment/layer/LayerBuilder.java, src/main/java/amidst/gui/main/menu/AmidstMenuBuilder.java
I found that the interpolation can sometimes be unwanted, especially if the computer you're using doesn't support hardware acceleration.
=> Allow switching between interpolation methods
