toolbox4minecraft/amidst

- src/main/java/amidst/Settings.java
- src/main/java/amidst/gui/profileselect/ProfileSelectPanel.java
- src/main/java/amidst/gui/profileselect/ProfileSelectWindow.java
- src/main/java/amidst/settings/MultipleStringsSetting.java
- src/main/java/amidst/settings/SettingBase.java
- src/main/java/amidst/settings/StringSetting.java
When Amidst is started without settings file, it creates a settings file with default values. One of the default values was null, which is not allowed as a value in a preference store. I changed it to use the empty String instead. I also added some checks to ensure this does not happen again.
[crash] Amidst crashed!
[crash] java.lang.NullPointerException
at java.util.prefs.AbstractPreferences.put(AbstractPreferences.java:241)
at amidst.settings.StringSetting.update(StringSetting.java:22)
at amidst.settings.StringSetting.update(StringSetting.java:7)
at amidst.settings.SettingBase.set(SettingBase.java:35)
at amidst.settings.SettingBase.restore(SettingBase.java:19)
at amidst.settings.StringSetting.<init>(StringSetting.java:12)
at amidst.Settings.<init>(Settings.java:57)
at …
> fixed a NullPointerException on startup

- src/main/java/amidst/gui/crash/CrashWindow.java
This is to prevent accidental changes while copying the crash report.
> made the message in the crash window uneditable

- src/devtools/java/amidst/devtools/GenerateUpdateInformationJson.java
Ensures that update information documents are only generated for stable releases, meaning a release that is not a pre-release.
> generate update information only for stable releases

- src/devtools/java/amidst/devtools/GenerateRecognisedVersionList.java
- src/devtools/java/amidst/devtools/settings/DevToolsSettings.java
- src/main/java/amidst/mojangapi/minecraftinterface/RecognisedVersion.java
- src/main/java/amidst/mojangapi/world/versionfeatures/DefaultVersionFeatures.java
* added a devtool to generate the entries of the enum RecognisedVersion
* replaced the existing enum entries by the generated list
* kept the entries that were included in the enum, but that are already removed from the launcher (and thus not generated)
> Dev tool generate recognised version list

- src/main/java/amidst/Amidst.java
- src/main/java/amidst/Application.java
- src/main/java/amidst/gui/main/Actions.java
- src/main/java/amidst/gui/main/MainWindow.java
- src/main/java/amidst/gui/main/menu/LayersMenu.java
- src/main/java/amidst/gui/profileselect/LocalProfileComponent.java
- src/main/java/amidst/gui/profileselect/ProfileSelectWindow.java
- src/main/java/amidst/mojangapi/MojangApi.java
- src/main/java/amidst/mojangapi/MojangApiBuilder.java
- src/main/java/amidst/mojangapi/file/DotMinecraftDirectoryNotFoundException.java
- src/main/java/amidst/mojangapi/file/json/launcherprofiles/LauncherProfileJson.java
- src/main/java/amidst/mojangapi/world/WorldBuilder.java
- src/main/java/amidst/mojangapi/world/icon/WorldIcon.java
- src/main/java/amidst/mojangapi/world/icon/producer/PlayerProducer.java
- src/main/java/amidst/mojangapi/world/icon/producer/SpawnProducer.java
- src/main/java/amidst/mojangapi/world/icon/producer/StrongholdProducer.java
- src/main/java/amidst/mojangapi/world/icon/producer/StructureProducer.java
* the save capture image dialog is now a save dialog
* the save capture image dialog now suggests a meaningful name
* removed obvious dimension information from the world icons
* added a meaningful error message when there is no valid .minecraft directory
* fixed an issue with the "(Default)" launcher profile
* added the minecraft profile name to the main window title
* removed the Enabled All Layers menu item when if has no effect
* moved the Player Icons menu item from the Overworld section to the dimension independent section
> Bug fixing

- src/main/java/amidst/gui/main/viewer/Drawer.java
Changes the void so it's no longer scaled and translated with the End islands, instead they "float" in a parallax layer above it.
You might have made this change already, or have better ideas how to do it.
> Display Void texture in parallax.

- src/main/java/amidst/gui/profileselect/LocalProfileComponent.java
When a profile is selected via the profile select window, a log message is written that contains the profile name and the real Minecraft versionId (the recognised versionId was always logged later on). This enables us to quickly identify bug reports about modded Minecraft versions.
> added logging information about the selected launcher profile

- src/main/java/amidst/gui/main/viewer/widget/DebugWidget.java
- src/main/java/amidst/gui/main/viewer/widget/Widget.java
Previously, clicking on a text widget did not trigger a select world icon operation. However, the text widget does not do anything with the click event. I think it is more intuitive to select the underlying world icon.
> fixed widgets to not catch unrelated mouse events

- src/main/java/amidst/fragment/colorprovider/TheEndColorProvider.java
- src/main/java/amidst/mojangapi/world/oracle/EndIsland.java
- src/main/java/amidst/mojangapi/world/oracle/EndIslandOracle.java
This problem is most visually noticeable when the grid is turned on - because (0,0) wasn't passing through the center of the Dragon's island, but fixing this also *slightly* improves teleport coordinates and using F3 coords to make sense of the map (by about 11.3 blocks).
> Fix 8-by-8 block misalignment of End Islands map

- src/main/java/amidst/threading/ThreadMaster.java
If a thread is a daemon thread, it does not keep the JVM alive. This means, that if all non-daemon threads are terminated, the JVM will just terminate all daemon threads and exit. This is a bad thing, if the daemon thread is currently writing to a file, because this will corrupt the file. Since the worker threads are used for IO, they should not be daemon threads.
> changed worker threads to be no daemon threads

- src/main/java/amidst/Amidst.java
- src/main/java/amidst/gui/crash/CrashWindow.java
Before, when there was a bug in the drawing loop this would have caused Amidst to open up to 50 crash windows per second (Amidst is capped at 50 FPS), which is really bad. Also, it is very likely that such bugs would not be reported, because the bug report cannot be copied.
Now, only one CrashWindow is opened and the displayed error message is updated when more crashes occur.
> converted the CrashWindow into a singleton

- src/main/java/amidst/Application.java
- src/main/java/amidst/CommandLineParameters.java
- src/main/java/amidst/mojangapi/world/SeedHistoryLogger.java
- src/main/java/amidst/mojangapi/world/WorldBuilder.java
The new format for text seeds is:
recognised version name, timestamp, seed as long, seed text
The new format for numeric seeds is:
recognised version name, timestamp, seed as long
Note that there is no "," at the end, to be able to distinguish it from the empty seed text "".
I also adjusted some log messages.
> adjusted format of the seed history file

- travis-ci/wrapper-for-windows/pom.xml
`headerType=console` which implies `stayAlive=true` fixes this issue. Also, I was not able to notice any bad side-effect of this setting on the GUI.
> fixed the windows wrapper to display stdout

- src/main/java/amidst/Amidst.java
This is because the Windows look and feel does not display checkboxes for menu items that have an icon. Also, the majority of the GUI is drawn by an own painting method, which does not rely on the look and feel. Thus, the decision to switch it should not have a great impact on the usability. Another advantage of this change is, that now all systems use the same look and feel, which should lower the chance of bugs happening on only one type of system.
> switched windows to use the default Java look and feel

- travis-ci/wrapper-for-windows/pom.xml
headerType=console which implies stayAlive=true fixes this issue. Also, I was not able to notice any bad side-effect of this setting on the GUI. (reverted from commit f1aa607c69f11cd2a82612b9a745c9ea9c4b6cf9)
This was reverted, because there is indeed an undesireable side-effect: A dos-box is opened, displaying stdout.
> revert: fixed the windows wrapper to display stdout

- src/main/java/amidst/Amidst.java
- src/main/java/amidst/AmidstSettings.java
- src/main/java/amidst/Application.java
- src/main/java/amidst/gui/main/Actions.java
- src/main/java/amidst/gui/main/menu/AmidstMenuBuilder.java
This is a workaround for the white window issue described in #81 and #43. It adds a setting to completely disable the Graphics Acceleration. You can activate this setting by using the key stroke **CTRL + A** in the main window. You will not get any feedback after doing do. Also, you need to restart Amidst for the changes to take effect.
I am not sure whether we should publish this. It might lead to issues like the following:
The user disables Graphics Acceleration without knowing it by accidentally clicking around in the settings or by hitting **CTRL + A**. After the next restart, the Graphics performance is very bad. He does not know were this comes from and is lost. He might report a bug, but he might as well ignore it and live with the bad performance. This would be a great reduction …
> added setting graphicsAcceleration

- src/main/java/amidst/Amidst.java
It caused performance issues: With OpenGL I get only up to about 40 FPS. Without I get the full 50 FPS.
This should not cause any additional issues, because it is also the behavior of Amidst v3.7.
> disabled OpenGL on Linux

- src/main/java/amidst/gui/main/MainWindow.java
I am affected by Issue #134 and I suggest using the keyTyped event instead keyPressed. This way + and - will work for zoom no matter how they are generated by the user's keyboard (even the keypad).
> Make zoom in/out key events work for all keyboard layouts

- src/main/java/amidst/Amidst.java
- src/main/java/amidst/gui/main/Actions.java
- src/main/java/amidst/gui/main/PNGFileFilter.java
- src/main/java/amidst/mojangapi/file/DotMinecraftDirectoryFinder.java
- src/main/java/amidst/mojangapi/file/LibraryFinder.java
- src/main/java/amidst/mojangapi/world/icon/producer/SpawnProducer.java
- src/main/java/amidst/mojangapi/world/icon/producer/StrongholdProducer_Base.java
- src/main/java/amidst/mojangapi/world/icon/producer/StructureProducer.java
- src/main/java/amidst/mojangapi/world/icon/type/DefaultWorldIconTypes.java
- src/main/java/amidst/util/FileExtensionChecker.java
- src/main/java/amidst/util/OperatingSystemDetector.java
- src/test/java/amidst/mojangapi/world/testworld/DefaultTestWorldDirectoryDeclaration.java
The conversion depends on the operating system's current Locale. Thus, it is not deterministic.
* I explicitly stated the filenames of the icons, instead of relying on the enum name.
* I collected all other occurences of toLowerCase in utility methods and made sure they are used correctly.
* toUpperCase has the same issue, but is currently not used by Amidst.
> fixed String.toLowerCase() issues

- src/main/java/amidst/mojangapi/file/json/PlayerInformationRetriever.java
- src/main/java/amidst/mojangapi/world/player/PlayerInformation.java
In case of not being able to retrieve player's head by name or skin url amidst opens an error window. With this fix a default Steve's head is tried first before it returns null. I guess we could also use supplied "player.png" instead.
> Retrieve Steve's head instead of returning null

- src/main/java/amidst/gui/main/MainWindow.java
- src/main/java/amidst/gui/main/PerMainWindowInjector.java
This prevents Amidst from creating a second resource intensive MojangApi, which is currently unnecessary.
> added checks for the seed search feature toggle

- src/main/java/amidst/mojangapi/world/biome/Biome.java
A small change to the `Biome` class; all biome variants (except Ice Plains Spikes) use the same color as their base; so there is no need to re-specify it.
(Are you certain we need to regenerate the Biome Color Table ? The special case of the Ice Plains Spikes is handled, so no biome color is modified.)
> Reuse base biome colors for biome variants

- src/main/java/amidst/gui/main/Actions.java
- src/main/java/amidst/gui/main/WorldSwitcher.java
- src/main/java/amidst/gui/seedsearcher/SeedSearcher.java
- src/main/java/amidst/gui/seedsearcher/SeedSearcherWindow.java
- src/main/java/amidst/mojangapi/RunningLauncherProfile.java
- src/main/java/amidst/mojangapi/world/WorldBuilder.java
- src/main/java/amidst/mojangapi/world/WorldOptions.java
- src/test/java/amidst/mojangapi/mocking/FakeWorldBuilder.java
- src/test/java/amidst/mojangapi/world/testworld/TestWorldDeclaration.java
- src/test/java/amidst/mojangapi/world/testworld/storage/json/WorldMetadataJson.java
Create the WorldOptions class to regroup WorldSeed, WorldType and the configuration string into a single object.
Should we modify the WorldType selection dialog to allow the user to also provide a configuration string to use for all worlds, and if so, should this be included in this PR ?
> Create WorldOptions class

- src/main/java/amidst/mojangapi/file/json/launcherprofiles/LauncherProfileJson.java
- src/main/java/amidst/mojangapi/file/json/launcherprofiles/ProfileType.java
Add support for the default profiles used by the Windows launcher : 
- Latest version: `"type": "latest-release"`, equivalent to the "bugged" default profile of the legacy launcher
- Latest snapshot: `"type": "latest-snapshot"`, this was improperly detected as the legacy default profile before
This fixes #377.
> Display correct name and version for Windows default profiles

- src/main/java/amidst/mojangapi/world/WorldBuilder.java
- src/main/java/amidst/mojangapi/world/icon/locationchecker/VillageLocationChecker.java
- src/main/java/amidst/mojangapi/world/versionfeatures/DefaultVersionFeatures.java
- src/main/java/amidst/mojangapi/world/versionfeatures/VersionFeatures.java
Since Minecraft 16w20a, villages can spread into invalid biomes, which means that villages rejected by the [`VillageAlgorithm`](https://github.com/toolbox4minecraft/amidst/blob/master/src/main/java/amidst/mojangapi/world/icon/locationchecker/VillageAlgorithm.java) should be accepted in 16w20a or higher.
This PR disable the `VillageAlgorithm` check accordingly, and all 3 villages mentioned in #117 now correctly appear in Amidst.
> Fix some false negative villages

- .travis.yml
`oraclejdk8` is no longer supported by Travis CI.
> Use openjdk instead of oraclejdk for Travis CI.

- src/main/java/amidst/CommandLineParameters.java
- src/main/java/amidst/PerApplicationInjector.java
- src/main/java/amidst/gui/main/MainWindow.java
- src/main/java/amidst/gui/main/PerMainWindowInjector.java
- src/main/java/amidst/mojangapi/LauncherProfileRunner.java
- src/main/java/amidst/mojangapi/RunningLauncherProfile.java
- src/main/java/amidst/mojangapi/world/WorldType.java
- src/test/java/amidst/devtools/WorldGenerationBencher.java
Add -seed command line argument to start Amidst with a particular world seed selected. This implements feature #461.
I've tried my best to follow https://github.com/toolbox4minecraft/amidst/wiki/Supporting-the-Development. I have announced my intention in #461, unfortunately I have not received any response from the maintainers. :-( If this PR is not accepted, please let me know what I need to fix rather than just close it outright.
> Add -seed command line argument

- .gitignore
- src/main/java/amidst/CommandLineParameters.java
- src/main/java/amidst/PerApplicationInjector.java
- src/main/java/amidst/mojangapi/file/MinecraftInstallation.java
This is the second part of #461. This patch adds a -profile command line option. While technically equivalent to using -mcjson and -mcjar, this makes for a simpler user interface. You can just specify "-profile 1.32.2" (if that's what your profile is called) to select it, instead of looking up the correct path to your minecraft directory and the corresponding version json and jar files.
-profile cannot be used together with -mcjson and -mcjar. I'm limiting the use to local profiles (I don't fully understand the remote profiles, and I don't want to rely on remote query to properly parse command line options), but as far as I understand, this is the same limitation that using -mcjar and -mcjson sets.
I also added a patch for .gitignore. It was bugging me that it didn't work correctly with …
> Add -profile as a CLI option for easier selection of profile.

- src/main/java/amidst/mojangapi/minecraftinterface/local/DefaultClassTranslator.java
- src/main/java/amidst/mojangapi/minecraftinterface/local/LocalMinecraftInterface.java
- src/main/java/amidst/mojangapi/minecraftinterface/local/SymbolicNames.java
The threads that register all of the datafixers take up a TON of CPU usage for a few minutes after loading the Registry class, and it doesn't help us in any way. We can just stop them a bit after they are created by getting the ExecutorService running them. I couldn't find a way to load the class without the threads being created, so I just did this instead.
Also instead of manually importing every field in the SymbolicNames, I just imported all of them. I feel like there may have been a reason for this, so feel free to change it back.
**EDIT**: The reason I don't use the method for this built into `Util` is because it requests a shutdown to the threads, waits a few seconds for them to shutdown, and then if it isn't already shut down, forcefully shuts the threads down. In my testing, the …
> After loading registry, stop datafixer threads

- src/main/java/amidst/gui/main/Actions.java
- src/main/java/amidst/gui/main/viewer/Zoom.java
- src/main/java/amidst/gui/main/viewer/widget/OffsetWidget.java
Following #722, this PR implements some changes to the zoom functionality:
- Each zoom level now corresponds to a `pow(2, 1/8) ~= 1.09` increase in the zoom scale, instead of  a `1.1` increase. This allow to hit exact powers of two every 8 levels.
- The keyboard zoom controls now increase or decrease the zoom by 4 levels (a `sqrt(2)` factor).
> Some zoom improvements

- src/main/java/amidst/clazz/real/RealClass.java
- src/main/java/amidst/clazz/real/RealClasses.java
- src/main/java/amidst/clazz/symbolic/SymbolicClassBuilder.java
- src/main/java/amidst/clazz/symbolic/declaration/SymbolicParameterDeclaration.java
- src/main/java/amidst/clazz/symbolic/declaration/SymbolicParameterDeclarationList.java
- src/main/java/amidst/mojangapi/minecraftinterface/RecognisedVersion.java
* Fix a method in RealClass that sometimes didn't work as intended
* Removed the class maximum file size as it wasn't detecting some classes in b1.7.3, replaced it with seeing if the file is a class file
* Add an option for symbolic and real arrays in class detection
* Fixed the magic string for b1.9-pre1
> Small changes that may help out in the future

- src/main/java/amidst/gui/export/BiomeExporterDialog.java
- src/main/java/amidst/gui/main/WorldSwitcher.java
- src/main/java/amidst/gui/main/viewer/ViewerFacade.java
- src/main/java/amidst/gui/seedsearcher/SeedSearcher.java
- src/main/java/amidst/mojangapi/RunningLauncherProfile.java
- src/main/java/amidst/mojangapi/minecraftinterface/LoggingMinecraftInterface.java
- src/main/java/amidst/mojangapi/minecraftinterface/MinecraftInterface.java
- src/main/java/amidst/mojangapi/minecraftinterface/legacy/LegacyMinecraftInterface.java
- src/main/java/amidst/mojangapi/minecraftinterface/legacy/_1_13MinecraftInterface.java
- src/main/java/amidst/mojangapi/minecraftinterface/local/LocalMinecraftInterface.java
- src/main/java/amidst/mojangapi/world/World.java
- src/main/java/amidst/mojangapi/world/WorldBuilder.java
- src/main/java/amidst/mojangapi/world/WorldSeed.java
- src/main/java/amidst/mojangapi/world/oracle/BiomeDataOracle.java
- src/main/java/amidst/mojangapi/world/versionfeatures/DefaultVersionFeatures.java
- src/main/java/amidst/util/ArrayCache.java
- src/main/java/amidst/util/FaillibleFunction.java
- src/test/java/amidst/mojangapi/mocking/BenchmarkingMinecraftInterface.java
- src/test/java/amidst/mojangapi/mocking/FakeMinecraftInterface.java
- src/test/java/amidst/mojangapi/mocking/FakeWorldBuilder.java
- src/test/java/amidst/mojangapi/mocking/RequestStoringMinecraftInterface.java
- src/test/java/amidst/mojangapi/world/test/VersionFeaturesTest.java
This refactors all `MinecraftInterface`s to allow creating multiple worlds at the same time with a single `MinecraftInterface` instance. As a consequence, the Amidst world disposing logic (via `World.dispose()`) isn't necessary anymore, and has been removed.
Additionally, it should now be possible to switch worlds while an export operation (see #716) is in process; I still need to do more testing to be sure that nothing breaks before making this change.
> Add support for multiple worlds on a single MinecraftInterface

- src/main/java/amidst/mojangapi/world/icon/type/EndCityWorldIconTypeProvider.java
Fixes #838.
Would likely make more sense to pass chunks along as a `long`, which was also mentioned in `StructureProducer`: https://github.com/toolbox4minecraft/amidst/blob/57444ba1268523102687e1e7b6b2057e39c1e3b5/src/main/java/amidst/mojangapi/world/icon/producer/StructureProducer.java#L53-L75
Perhaps that's a change worth making?
> Fix integer overflow in end city icon generation

- src/main/java/amidst/fragment/drawer/WorldIconDrawer.java
Before, I forgot to reset the scaling mode after every structure in the method. This fixes that.
> Fix interpolation on structures
